# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moodelizer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'

  # Pods for Moodelizer

  target 'MoodelizerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
